const fs=require('fs'); 
const p='frontend/src/shared/components/responsive/ResponsivePageLayout.jsx'; 
let lines=fs.readFileSync(p,'utf8').split(/\r?\n/); 
const hookIndex=lines.findIndex(line=>line.includes(`const { isMobile, showBottomNav, isCollapsed } = useSidebar();`)); 
if(hookIndex===-1) throw new Error(`hook not found`); 
lines.splice(hookIndex,1,`  const { isMobile, showBottomNav, isCollapsed, isSidebarVisible } = useSidebar();`,`  const sidebarOffset = !isMobile && isSidebarVisible`,`    ? (isCollapsed ? 'var(--sidebar-width-collapsed)' : 'var(--sidebar-width-expanded)')`,`    : '0px';`); 
const shellIndex=lines.findIndex(line=>line.includes(`<div className=\"h-screen overflow-hidden\" style=`)); 
if(shellIndex===-1) throw new Error(`shell not found`); 
lines.splice(shellIndex,1,`    <div`,`      className=\"h-screen overflow-hidden\"`,`      style={{`,`        background: 'var(--bg-canvas)',`,`        '--sidebar-width-expanded': '284px',`,`        '--sidebar-width-collapsed': '64px',`,`        '--sidebar-width': sidebarOffset,`,`        '--header-height': '64px',`,`      }}`,`    >`); 
if(sidebarIndex===-1) throw new Error(`sidebar line not found`); 
const mainIndex=lines.findIndex(line=>line.includes(`<main className=\"flex flex-col overflow-hidden min-w-0 h-screen\"`)); 
if(mainIndex===-1) throw new Error(`main not found`); 
lines.splice(mainIndex,1,`      <main`,`        className=\"flex min-w-0 h-screen flex-col overflow-hidden\"`,`        style={{`,`          marginLeft: sidebarOffset,`,`          width: isMobile ? '100%%' : __BT__calc(100%% - ${sidebarOffset})__BT__,`,`          minHeight: '100vh',`,`        }}`,`      >`); 
lines=lines.map(line=>line.replace(/__BT__/g,String.fromCharCode(96))); 
fs.writeFileSync(p,lines.join(`\n`),`utf8`); 
