export const DEFAULT_FEATURE_FLAGS = {
  dashboard: true,
  tasks: true,
  kanban: true,
  calendar: true,
  notifications: true,
  self_attendance: true,
  projects: true,
  my_projects: true,
  sprints: true,
  gantt: true,
  resources: true,
  analytics: true,
  hr_dashboard: true,
  hr_attendance: true,
  hr_leaves: true,
  hr_calendar: true,
  reallocation: true,
  email_center: true,
  teams: true,
  users: true,
  settings: true,
  audit_log: true,
  changelog: true,
  geofencing: true,
  verification: true,
  feature_matrix: true,
};

export const FEATURE_KEY_BY_PATH = {
  '/dashboard': 'dashboard',
  '/tasks': 'tasks',
  '/kanban': 'kanban',
  '/calendar': 'calendar',
  '/notifications': 'notifications',
  '/self-attendance': 'self_attendance',
  '/projects': 'projects',
  '/my-projects': 'my_projects',
  '/sprints': 'sprints',
  '/resources': 'resources',
  '/analytics': 'analytics',
  '/projects/gantt': 'gantt',
  '/hr/dashboard': 'hr_dashboard',
  '/hr/attendance': 'hr_attendance',
  '/hr/leaves': 'hr_leaves',
  '/hr/calendar': 'hr_calendar',
  '/hr/reallocation': 'reallocation',
  '/hr/email-center': 'email_center',
  '/teams': 'teams',
  '/users': 'users',
  '/settings': 'settings',
  '/audit-log': 'audit_log',
  '/changelog': 'changelog',
  '/geofence-management': 'geofencing',
  '/verification-settings': 'verification',
  '/feature-matrix': 'feature_matrix',
};

export const FEATURE_FLAG_SECTIONS = [
  {
    id: 'core',
    label: 'Core Workspace',
    items: [
      { key: 'dashboard', label: 'Dashboard', path: '/dashboard' },
      { key: 'tasks', label: 'Tasks', path: '/tasks' },
      { key: 'kanban', label: 'Kanban', path: '/kanban' },
      { key: 'calendar', label: 'Calendar', path: '/calendar' },
      { key: 'notifications', label: 'Notifications', path: '/notifications' },
      { key: 'self_attendance', label: 'Self Attendance', path: '/self-attendance' },
    ],
  },
  {
    id: 'projects',
    label: 'Projects',
    items: [
      { key: 'projects', label: 'All Projects', path: '/projects' },
      { key: 'my_projects', label: 'My Projects', path: '/my-projects' },
      { key: 'sprints', label: 'Sprints', path: '/sprints' },
      { key: 'gantt', label: 'Gantt', path: '/projects/gantt' },
      { key: 'resources', label: 'Resources', path: '/resources' },
      { key: 'analytics', label: 'Analytics', path: '/analytics' },
    ],
  },
  {
    id: 'hr',
    label: 'HR',
    items: [
      { key: 'hr_dashboard', label: 'HR Dashboard', path: '/hr/dashboard' },
      { key: 'hr_attendance', label: 'Attendance', path: '/hr/attendance' },
      { key: 'hr_leaves', label: 'Leaves', path: '/hr/leaves' },
      { key: 'hr_calendar', label: 'HR Calendar', path: '/hr/calendar' },
      { key: 'reallocation', label: 'Reallocation', path: '/hr/reallocation' },
      { key: 'email_center', label: 'Email Center', path: '/hr/email-center' },
      { key: 'teams', label: 'Teams', path: '/teams' },
      { key: 'users', label: 'Users', path: '/users' },
    ],
  },
  {
    id: 'system',
    label: 'System',
    items: [
      { key: 'settings', label: 'Settings', path: '/settings' },
      { key: 'audit_log', label: 'Audit Log', path: '/audit-log' },
      { key: 'changelog', label: 'Change Log', path: '/changelog' },
      { key: 'geofencing', label: 'Geofencing', path: '/geofence-management' },
      { key: 'verification', label: 'Verification', path: '/verification-settings' },
      { key: 'feature_matrix', label: 'Feature Matrix', path: '/feature-matrix' },
    ],
  },
];
